---
title: "[Final Project] Exploring Tariff Policies' Efficacy on Reshoring Global Supply Chain - Within Context of 2018 U.S.-China Tariff War"
author: "Sojung Hwang"

date: last-modified
toc: true

bibliography: references.bib

format: 
  html: 
    self-contained: true

editor: source
---

# Introduction

With the second Trump presidency, the tariff war between the U.S. and China has escalated, with both sides sequentially raising tariffs. As of May, after 100 days into Trump’s second term, the U.S. has imposed a record-high tariff level of 145% on Chinese imports [@BBC2025]. Yet, the tariff war is not a new concept. This research explores the relationship between tariffs and global supply chain (GVC) restructuring, with the question: How did multinational firms (MNCs) restructure their supply chains in response to the 2018 U.S. tariffs on Chinese imports, and what factors explain their decisions? By analyzing data from the first Trump presidency, this study aims to inform current debates over the effectiveness of tariffs.

Preliminary research on the impact of Trump's 2018 aggressive tariff shock focuses on two aspects: the policy's rationale and its real-world impact on GVCs. The Trump administration claimed that tariffs would encourage U.S. multinationals to reshore operations from China by making them costlier. Officials argued this would revitalize domestic manufacturing jobs lost to cheaper overseas labor [@BBC2019].

However, contrary to the administration's expectations, current academic research suggests the 2018 tariff impose failed at triggering reshoring. 

However, most academic findings suggest otherwise. The 2018 tariffs did not trigger widespread reshoring. According to the World Bank, while some nearshoring occurred, but this was exclusive to border countries, and there is no consistent evidence of large-scale reshoring. The resilience of existing GVCs, or their “stickiness,” helps explain this. Firms, driven by long-term profitability, consider the sunk costs embedded in their offshore operations. These can include various investments already put into the current GVC. For example, in buidling a manufacturing factory in China, an American MNC's sunk costs will include capital investment, regulatory compliance, skilled labor training, etc.. Unless trade shocks are severe and lasting, relocating production back to the U.S. is often not cost-effective. Moreover, reshoring itself involves new sunk costs, such as rebuilding domestic capacity and reintegrating previously outsourced functions, making it an even less attractive option [@Freund2023].

Instead of reshoring, the tariff shock led to a redirection of U.S. import sourcing. Countries such as Taiwan, Mexico, and Vietnam emerged as major beneficiaries. A UNCTAD report shows that China’s lost U.S. exports were redirected to these countries, particularly in office machinery and communications equipment.For instance, Taiwan was the largest beneficiary, accounting for additional exports to the U.S. of almost 4.2 billion USD in the first half of 2019. The benefits have been largely related to an increase in exports of office machinery and communication equipment [@Nicita2019]. This shift is also visible in aggregate trade data. After the first round of tariffs in July 2018, China’s share of U.S. imports declined by about 3 percentage points, while imports from “Other Asia” (e.g., Taiwan, Thailand, Vietnam) rose by a similar margin [@Grossman2024].

In short, Trump’s 2018 tariff policy failed to achieve their reshoring goals. Rather, firms redirected their GVC to alternatie manufacturing hubs in countries such as Taiwan, Mexico, and Vietnam. Academic literature explains why reshoring did not happen through concepts such as GVC stickiness and suck costs but there is less discussion on why the said specific countries benefited. This paper seeks to investigate relocation pattern more closely, focusing on the drivers that made countries like Vietnam, Taiwan, and Mexico attractive destinations. 

With renewed U.S.-China tensions, this research offers insights into the efficacy of tariffs as a tool for GVC reconfiguration. It also contributes to our understanding of how developing and middle-income countries can capitalize on global trade disruptions. The ability of countries like Vietnam and Mexico to absorb displaced supply chains highlights broader implications for utilizing unprecedented shocks as opportunities for economic growth.

# Hypothesis

This section develops multiple hypotheses to explain how firms responded to the 2018 U.S. tariffs on Chinese imports and why certain countries became trade diversion beneficiaries. Specifically, it explores whether existing production linkages to China positioned said countries to benefit from trade diversion. Rather than reshoring, firms may have sought locations that allowed them to maintain some operational continuity with their China-based suppliers.

## H: Countries with higher levels of GVC integration with China would have experienced greater increases in U.S. import share following the 2018 tariffs on Chinese goods.






# Research Design
## 



# Findings
# Empirical Extension
# Discussion and Policy Implications


